name: Generate Weekly Workouts

on:
  schedule:
    # Run every Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # <-- This allows manual triggering

jobs:
  generate_workouts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pandas

      - name: Run the workout script
        run: python gen_workouts.py > workout_output.txt

      - name: Create an issue from a file
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Weekly Workouts for $(date +'%Y-%m-%d')
          content-filepath: ./workout_output.txt
