name: Generate Weekly Workouts

on:
  schedule:
    # Run every Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # <-- This allows manual triggering

jobs:
  generate_workouts:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Date for Title
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pandas openai

      - name: Run the workout script
        run: python gen_workouts.py > workout_output.txt
      
      - name: Run the advice script
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: python gen_advice.py

    - name: Close workout-plan issues
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo
          const labelName = "workout-plan"
          
          const issues = await github.paginate(
            github.rest.issues.listForRepo,
            {
              owner,
              repo,
              state: "open",
              labels: labelName,
            }
          )
          
          for (const issue of issues) {
            await github.rest.issues.update({
              owner,
              repo,
              issue_number: issue.number,
              state: "closed"
            })
            
            console.log(`Closed issue #${issue.number}`)
          }

      - name: Create an issue from a file
        id: create_issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Weekly Workouts for ${{ steps.date.outputs.date }}
          content-filepath: ./workout_output.txt
          labels: workout-plan

      - name: Add comment with trainer advice
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create_issue.outputs.issue-number }}
          body-path: ./workout_advice.md
          token: ${{ secrets.GITHUB_TOKEN }}

